### ISSUE TITLE
Bussit liikkuu takaperin

### ISSUE THREAD

**Issue by EskelinenAntti** [ssuonsyrja/2017jotu7#1]
Kartalla näkyvät bussit kulkevat takaperin (nuoli tulosuuntaan) Androidilla samsungin selaimella.

**Comment by varesa** [comment]
Hei,

Onko sinulla päällä asetus "Pisarat noudattavat fysiikan lakeja"? Se kääntää pisaroiden/nuolen suunnan

**Comment by EskelinenAntti** [comment]
Oho
